name: Publish Design Tokens

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to allow the bot to push commits

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build tokens
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit build artifacts and Publish
        run: |
          git add --force design-tokens-build/
          if ! git diff-index --quiet HEAD; then
            echo "Changes detected in build artifacts. Committing them."
            git commit -m "build: generate new token assets"
          else
            echo "No changes in build artifacts. Nothing to publish."
            exit 0
          fi
          npm version patch -m "chore(release): publish new tokens v%s"
          git push --follow-tags
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Trigger rk-designsystem Update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: danieltunetek/rk-designsystem
          event-type: new-design-tokens-version

      - name: Trigger rk-conference-demo Update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: danieltunetek/rk-conference-demo
          event-type: new-design-tokens-version

      - name: Trigger norwegianredcross/DesignSystem Update
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT }}
          repository: norwegianredcross/DesignSystem # The new project
          event-type: new-design-tokens-version