name: Publish Design Tokens

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build tokens
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit, Push, and Publish
        run: |
          # Forcefully add the correct folder, overriding .gitignore
          git add --force design-tokens-build/

          # Check if there are any changes to commit
          if [[ -z $(git status --porcelain) ]]; then
            echo "No changes to publish."
            exit 0
          fi

          # Get the new version number before creating the tag
          new_version=$(npm version patch --no-git-tag-version)

          git commit -m "chore(release): publish new tokens ${new_version}"
          git tag ${new_version}
          git push --follow-tags
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}